# Fedora 31 (cgroup v2) on Vagrant
dist: bionic
language: generic
cache:
  directories:
  - /home/travis/.vagrant.d/boxes
env:
  global:
  - VAGRANT_VERSION=2.2.7
install:
- sudo apt-get remove -q -y 'docker*' && sudo rm -rf /etc/docker && curl -fsSL https://get.docker.com | sh
# https://github.com/alvistack/ansible-role-virtualbox/blob/6887b020b0ca5c59ddb6620d73f053ffb84f4126/.travis.yml#L30
- sudo apt-get install -q -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev && wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_$(uname -m).deb && sudo dpkg -i vagrant_${VAGRANT_VERSION}_$(uname -m).deb && rm -f vagrant_${VAGRANT_VERSION}_$(uname -m).deb
- sudo vagrant plugin install vagrant-libvirt
- sudo DOCKER_BUILDKIT=1 DOCKER_BUILD_FLAGS="--progress=plain" make binaries
script:
- sudo vagrant up && sudo mkdir -p /root/.ssh && sudo sh -c "vagrant ssh-config >> /root/.ssh/config"
- sudo ssh default /vagrant/hack/smoketest-binaries.sh --cri=containerd
- sudo ssh default /vagrant/hack/smoketest-binaries.sh --cri=crio
