version: "3"

services:
  master:
    image: rootlesscontainers/usernetes
    command:
      - --start=u7s-master-with-etcd.target
      - --cidr=10.0.100.0/24
# 2379/tcp: etcd, 8080/tcp: kube-apiserver, 10251/tcp: kube-scheduler, 10252/tcp: kube-controller-manager
      - --publish=0.0.0.0:2379:2379/tcp
      - --publish=0.0.0.0:8080:8080/tcp
      - --publish=0.0.0.0:10251:10251/tcp
      - --publish=0.0.0.0:10252:10252/tcp
      - --cni=flannel
      - --cri=
    privileged: true
    tty: true
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - usernetes
  node-crio:
    image: rootlesscontainers/usernetes
    command:
      - --start=u7s-node.target
      - --cidr=10.0.101.0/24
# 10250/tcp: kubelet, 8472/udp: flannel
      - --publish=0.0.0.0:10250:10250/tcp
      - --publish=0.0.0.0:8472:8472/udp
      - --kubeconfig=/home/user/usernetes/config/docker-compose-master.kubeconfig
      - --cni=flannel
      - --cri=crio
    privileged: true
    tty: true
    networks:
      - usernetes
  node-containerd:
    image: rootlesscontainers/usernetes
    command:
      - --start=u7s-node.target
      - --cidr=10.0.102.0/24
# 10250/tcp: kubelet, 8472/udp: flannel
      - --publish=0.0.0.0:10250:10250/tcp
      - --publish=0.0.0.0:8472:8472/udp
      - --kubeconfig=/home/user/usernetes/config/docker-compose-master.kubeconfig
      - --cni=flannel
      - --cri=containerd
    privileged: true
    tty: true
    networks:
      - usernetes
networks:
  usernetes:
