version: '2'
output: prefixed
tasks:
  rootlesskit:
    cmds:
      - ./boot/rootlesskit.sh
  dockerd:
    cmds:
      - ./boot/dockerd.sh
  kubelet-dockershim:
    cmds:
      - ./boot/kubelet-dockershim.sh
  crio:
    cmds:
      - ./boot/crio.sh
  kubelet-crio:
    cmds:
      - ./boot/kubelet-crio.sh
  containerd:
    cmds:
      - ./boot/containerd.sh
  kubelet-containerd:
    cmds:
      - ./boot/kubelet-containerd.sh
  etcd:
    cmds:
      - ./boot/etcd.sh
  kube-apiserver:
    cmds:
      - ./boot/kube-apiserver.sh
  kube-controller-manager:
    cmds:
      - ./boot/kube-controller-manager.sh
  kube-scheduler:
    cmds:
      - ./boot/kube-scheduler.sh
  kube-proxy:
    cmds:
      - ./boot/kube-proxy.sh
  kube-common:
    deps:
      - etcd
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
      - kube-proxy
  default-docker:
    deps:
      - rootlesskit
      - dockerd
      - kubelet-dockershim
      - kube-common
  default-docker-nokube:
     deps:
      - rootlesskit
      - dockerd
  default-crio:
    deps:
      - rootlesskit
      - crio
      - kubelet-crio
      - kube-common
  default-containerd:
    deps:
      - rootlesskit
      - containerd
      - kubelet-containerd
      - kube-common
  default:
    deps:
      - default-docker
