version: '2'
output: prefixed
tasks:
  rootlesskit:
    cmds:
      - ./boot/rootlesskit.sh
  dockerd:
    cmds:
      - ./boot/dockerd.sh
  kubelet-dockershim:
    cmds:
      - ./boot/kubelet-dockershim.sh
  crio:
    cmds:
      - ./boot/crio.sh
  kubelet-crio:
    cmds:
      - ./boot/kubelet-crio.sh
  containerd:
    cmds:
      - ./boot/containerd.sh
  kubelet-containerd:
    cmds:
      - ./boot/kubelet-containerd.sh
  etcd:
    cmds:
      - ./boot/etcd.sh
  etcd-init-data:
    cmds:
      - ./boot/etcd-init-data.sh
  kube-apiserver:
    cmds:
      - ./boot/kube-apiserver.sh
  kube-controller-manager:
    cmds:
      - ./boot/kube-controller-manager.sh
  kube-scheduler:
    cmds:
      - ./boot/kube-scheduler.sh
  kube-proxy:
    cmds:
      - ./boot/kube-proxy.sh
  kube-apiserver+kube-controller-manager+kube-scheduler:
    deps:
      - kube-apiserver
      - kube-controller-manager
      - kube-scheduler
  flanneld:
    cmds:
      - ./boot/flanneld.sh
  dockerd+kubelet-dockershim+kube-proxy:
    deps:
      - dockerd
      - kubelet-dockershim
      - kube-proxy
  crio+kubelet-crio+kube-proxy:
    deps:
      - crio
      - kubelet-crio
      - kube-proxy
  containerd+kubelet-containerd+kube-proxy:
    deps:
      - containerd
      - kubelet-containerd
      - kube-proxy
  docker-compose-master+etcd:
    deps:
      - rootlesskit
      - etcd
      - etcd-init-data
      - kube-apiserver+kube-controller-manager+kube-scheduler
  docker-compose-node-docker:
    deps:
      - rootlesskit
      - dockerd+kubelet-dockershim+kube-proxy
# NOTE: requires $U7S_FLANNEL=1 to be set
  docker-compose-node-docker+flanneld:
    deps:
      - docker-compose-node-docker
      - flanneld
  default-docker:
    deps:
      - rootlesskit
      - etcd
      - kube-apiserver+kube-controller-manager+kube-scheduler
      - dockerd+kubelet-dockershim+kube-proxy
  default-docker-nokube:
     deps:
      - rootlesskit
      - dockerd
  default-crio:
    deps:
      - rootlesskit
      - etcd
      - kube-apiserver+kube-controller-manager+kube-scheduler
      - crio+kubelet-crio+kube-proxy
  default-containerd:
    deps:
      - rootlesskit
      - etcd
      - kube-apiserver+kube-controller-manager+kube-scheduler
      - containerd+kubelet-containerd+kube-proxy
  default:
    deps:
      - default-docker
