name: Main
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: "System info"
      run: sh -xec "uname -a; docker info; cat /proc/cpuinfo; df -h"
    - uses: actions/checkout@v2
    - name: "Build image"
      run: DOCKER_BUILDKIT=1 docker build -t rootlesscontainers/usernetes .
    - name: "Prune cache (To avoid `node.kubernetes.io/disk-pressure` taint)"
      run: docker builder prune -a -f
    - name: "Smoke test (containerd)"
      run: ./hack/smoketest-docker.sh u7s-test-containerd rootlesscontainers/usernetes --cri=containerd
    - name: "Smoke test (CRI-O)"
      run: ./hack/smoketest-docker.sh u7s-test-crio rootlesscontainers/usernetes --cri=crio
    - name: "Smoke test (multi-node cluster with Flannel)"
      run: ./hack/smoketest-docker-compose.sh
